### PR TITLE
Fixes Bot init having a wrong argument, sending nickserv pass instead of serverpass.

### LINKED ISSUE #38: Not able to connect to password protected server
I'm running ircd-hybrid 7.2.2 on a ubuntu server. The server is running on 6669 and password protected.

I've added serverpass to the default.py. 

On starting jenny this is what i see
<pre>

Connecting to example.com:6669... connected!
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...
</pre>

On the server logs I see:
<pre>
[2012/1/25 12.35] Access denied: hal9k[A.B.C.D]
[2012/1/25 12.35] Unauthorized client connection from hal9k[hal9k@A.B.C.D] on [0.0.0.0/6669]
</pre>

I'm reasonably comfortable with python so I added some print debugging to modules/startup.py, but it seems the server throws me out before that.

eggdrop works out of the box :(

### PR DESCRIPTION
**Pull request by vista-**
Should fix #38

### CODE REVIEW

**Comment by kaneda** [comment]
This is supposed to be user password, AFAIK: https://github.com/sbp/phenny/blob/master/irc.py#L36

**Comment by vista-** [comment]
https://github.com/sbp/phenny/blob/master/irc.py#L93 suggests it is the server password that it's trying to send.

**Comment by kaneda** [comment]
@vista- that's probable. It doesn't ident here so I think you're right.

**Comment by kaneda** [comment]
@vista- Looks good. Can you squash this please?

**Comment by vista-** [comment]
@kaneda , I might have discovered a bug related to this yesterday, but I couldn't really fix it. To reproduce, try connecting to a server with both serverpass and password commented out from the config file, perhaps you can give me some insight on this.

**Comment by kaneda** [comment]
@vista- what's the bug?

**Comment by vista-** [comment]
Join a server with both nickserv and server password commented out from the config file, it will complain about config.password having "NoneType" instead of "string".

**Comment by kaneda** [comment]
@vista- that makes sense, and that's not part of jenni directly. Instead of setting serverpass to None why don't you do:
```python
try: serverpass = config.serverpass
except: serverpass = ""
```

**Comment by vista-** [comment]
Tried that, still getting this error:

http://puu.sh/fZOMC/4986f0fb08.png

**Comment by kaneda** [comment]
@vista- that looks like a bug related to not having password defined in default.py, unrelated to your change here. If password isn't in the file it should skip right over that, but you can add to that if statement as follows and test:
```python
if hasattr(jenni.config, 'nick') and jenni.config.nick not None and hasattr(jenni.config, 'password') and jenni.config.password not None:
```

**Comment by vista-** [comment]
Skip over 'that', meaning the line in bot.py, or sasl.py?

**Comment by vista-** [comment]
well, so much about that planned bugfix.

**Comment by kaneda** [comment]
@vista- can you test if my proposed fixed to sasl works, and if so, create a new PR for it?

**Comment by vista-** [comment]
@kaneda please elaborate, is the line you posted required above func() or the line in sasl.py?

**Comment by kaneda** [comment]
@vista- the line in sasl, since that's where it's exhibiting the bad behavior.

**Comment by vista-** [comment]
Yep, worked, PRing now.

**Pull request merged**
