### PR TITLE
Sorted modules

### PR DESCRIPTION
**Pull request by abjonnes**
resubmitting #164

### CODE REVIEW

**Comment by kaneda** [comment]
Looks good to me. Can you squash it please?

**Comment by abjonnes** [comment]
I've squashed the commits on my branch - unsure if I'm supposed to do that in an open pull request (I see mixed answers online). I don't see it updating here so maybe not :)

**Comment by kaneda** [comment]
@abjonnes http://davidwalsh.name/squash-commits-git

If you're using git < 2.0 then do ```git push -uf origin <yourbranchname>``` instead of ```git push -f```

**Comment by abjonnes** [comment]
@kaneda I've done that; I tried `git push -uf origin <yourbranchname>` too since I'm using 1.7.1 but it doesn't seem to have updated here.

**Comment by kaneda** [comment]
@abjonnes I have trouble believing that :P

**Comment by abjonnes** [comment]
I've done the following:
`git fetch upstream`
`git rebase -i upstream/master`
`git push origin sorted_modules -f`
`git push -uf origin sorted_modules`

`git log` shows the squashed commit, and it appears in the `sorted_modules` branch in my repo abjonnes@62236f85acbb7c04f98ab01ceede5e3c9322bbb1. Not sure what I'm doing wrong, sorry :\

**Comment by kaneda** [comment]
Weird. I can squash and merge this down for you tomorrow, don't worry about it.

**Pull request closed without merging**
